{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "d70d248e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Analyse du fichier en cours...\n",
      "\n",
      "=== RÉSULTATS D'EXTRACTION SIREN ===\n",
      "Fichier analysé: D:/Bureau/Stage La gazette/projet ia n°de siren/annonces légales/test annonce légale saone et loire 0206.txt\n",
      "SIREN valides trouvés: 32\n",
      "SIREN invalides trouvés: 0\n",
      "\n",
      "SIREN valides:\n",
      "  - 818467615\n",
      "  - 884297169\n",
      "  - 507384683\n",
      "  - 888617651\n",
      "  - 889671509\n",
      "  - 513603472\n",
      "  - 850847955\n",
      "  - 931808331\n",
      "  - 891748444\n",
      "  - 893609776\n",
      "  - 685550659\n",
      "  - 404146656\n",
      "  - 980904890\n",
      "  - 833143662\n",
      "  - 499901205\n",
      "  - 915366520\n",
      "  - 929199701\n",
      "  - 451132534\n",
      "  - 531997294\n",
      "  - 887913424\n",
      "  - 808775639\n",
      "  - 518776562\n",
      "  - 750626269\n",
      "  - 750583486\n",
      "  - 847815826\n",
      "  - 483629036\n",
      "  - 317587038\n",
      "  - 970506812\n",
      "  - 948790381\n",
      "  - 840026298\n",
      "  - 822894770\n",
      "  - 851006817\n",
      "Résultats sauvegardés dans: resultats/siren_extraits_20250612_105258.csv\n",
      "Résultats sauvegardés dans : resultats/siren_extraits_20250612_105258.json\n",
      "\n",
      "✅ Exctraction terminée avec succès!\n"
     ]
    }
   ],
   "source": [
    "import spacy\n",
    "from spacy.pipeline import EntityRuler\n",
    "from spacy import displacy\n",
    "from spacy.training import Example\n",
    "from spacy.tokens import DocBin\n",
    "import pandas as pd\n",
    "import json\n",
    "import re\n",
    "import numpy as np\n",
    "import os\n",
    "from datetime import datetime\n",
    "\n",
    "class SirenExtractor:\n",
    "    \"\"\"Classe pour extraire et valider les numéros SIREN depuis un texte\"\"\"\n",
    "    \n",
    "    def __init__(self, modele_spacy=\"fr_core_news_md\"):\n",
    "        \"\"\"Initialiser l'extracteur SIREN\"\"\"\n",
    "        self.nlp = self._configurer_nlp(modele_spacy)\n",
    "    \n",
    "    def _creer_patterns_siren(self):\n",
    "        \"\"\"Définir les patterns pour la détection des numéros SIREN\"\"\"\n",
    "        patterns = [\n",
    "            # SIREN sous forme de 9 chiffres consécutifs\n",
    "            {\"label\": \"SIREN\", \"pattern\": [{\"TEXT\": {\"REGEX\": r\"^\\d{9}$\"}}]},\n",
    "            \n",
    "            # SIREN sous forme de 3 groupes de 3 chiffres\n",
    "            {\"label\": \"SIREN\", \"pattern\": [\n",
    "                {\"TEXT\": {\"REGEX\": r\"^\\d{3}$\"}},\n",
    "                {\"TEXT\": {\"REGEX\": r\"^\\d{3}$\"}},\n",
    "                {\"TEXT\": {\"REGEX\": r\"^\\d{3}$\"}}\n",
    "            ]},\n",
    "            \n",
    "            # SIREN précédé de \"RCS\"\n",
    "            {\"label\": \"SIREN\", \"pattern\": [\n",
    "                {\"LOWER\": \"rcs\"},\n",
    "                {\"IS_ALPHA\": True, \"OP\": \"?\"},\n",
    "                {\"TEXT\": {\"REGEX\": r\"^\\d{9}$\"}}\n",
    "            ]},\n",
    "            \n",
    "            # SIREN précédé de \"RCS\" avec format 3-3-3\n",
    "            {\"label\": \"SIREN\", \"pattern\": [\n",
    "                {\"LOWER\": \"rcs\"},\n",
    "                {\"IS_ALPHA\": True, \"OP\": \"?\"},\n",
    "                {\"TEXT\": {\"REGEX\": r\"^\\d{3}$\"}},\n",
    "                {\"TEXT\": {\"REGEX\": r\"^\\d{3}$\"}},\n",
    "                {\"TEXT\": {\"REGEX\": r\"^\\d{3}$\"}}\n",
    "            ]},\n",
    "            \n",
    "            # SIREN avec mention explicite\n",
    "            {\"label\": \"SIREN\", \"pattern\": [\n",
    "                {\"LOWER\": {\"IN\": [\"siren\", \"siret\"]}},\n",
    "                {\"TEXT\": {\"REGEX\": r\"^\\d{9}$\"}}\n",
    "            ]},\n",
    "            \n",
    "            # SIREN avec séparateurs\n",
    "            {\"label\": \"SIREN\", \"pattern\": [\n",
    "                {\"LOWER\": {\"IN\": [\"siren\", \"siret\", \"rcs\"]}},\n",
    "                {\"TEXT\": {\"IN\": [\":\", \"n°\", \"numéro\", \"no\"]}},\n",
    "                {\"TEXT\": {\"REGEX\": r\"^\\d{9}$\"}}\n",
    "            ]},\n",
    "            \n",
    "            # SIREN avec tirets\n",
    "            {\"label\": \"SIREN\", \"pattern\": [\n",
    "                {\"TEXT\": {\"REGEX\": r\"^\\d{3}$\"}},\n",
    "                {\"TEXT\": \"-\"},\n",
    "                {\"TEXT\": {\"REGEX\": r\"^\\d{3}$\"}},\n",
    "                {\"TEXT\": \"-\"},\n",
    "                {\"TEXT\": {\"REGEX\": r\"^\\d{3}$\"}}\n",
    "            ]}\n",
    "        ]\n",
    "        return patterns\n",
    "    \n",
    "    def _configurer_nlp(self, modele_spacy):\n",
    "        \"\"\"Configurer le pipeline spaCy avec EntityRuler\"\"\"\n",
    "        try:\n",
    "            nlp = spacy.load(modele_spacy)\n",
    "        except OSError:\n",
    "            print(f\"Modèle {modele_spacy} non trouvé. Tentative avec fr_core_news_sm...\")\n",
    "            try:\n",
    "                nlp = spacy.load(\"fr_core_news_sm\")\n",
    "            except OSError:\n",
    "                print(\"Aucun modèle français trouvé. Utilisation du modèle blank...\")\n",
    "                nlp = spacy.blank(\"fr\")\n",
    "        \n",
    "        # Ajouter EntityRuler\n",
    "        if \"entity_ruler\" not in nlp.pipe_names:\n",
    "            ruler = nlp.add_pipe(\"entity_ruler\", before=\"ner\" if \"ner\" in nlp.pipe_names else \"last\")\n",
    "            patterns = self._creer_patterns_siren()\n",
    "            ruler.add_patterns(patterns)\n",
    "        \n",
    "        return nlp\n",
    "    \n",
    "    def valider_siren(self, siren_str):\n",
    "        \"\"\"Valider un numéro SIREN avec l'algorithme de Luhn\"\"\"\n",
    "        # Nettoyer le SIREN (garder seulement les chiffres)\n",
    "        siren = re.sub(r'\\D', '', str(siren_str))\n",
    "        \n",
    "        # Vérifier la longueur et que ce sont des chiffres\n",
    "        if len(siren) != 9 or not siren.isdigit():\n",
    "            return False\n",
    "        \n",
    "        # Algorithme de Luhn\n",
    "        total = 0\n",
    "        for i, digit in enumerate(siren):\n",
    "            n = int(digit)\n",
    "            if i % 2 == 1:  # Position paire (en partant de 0)\n",
    "                n *= 2\n",
    "                if n > 9:\n",
    "                    n -= 9\n",
    "            total += n\n",
    "        \n",
    "        return total % 10 == 0\n",
    "    \n",
    "    def extraire_numeros_siren_regex(self, texte):\n",
    "        \"\"\"Extraire les numéros SIREN avec regex (méthode de fallback)\"\"\"\n",
    "        # Pattern pour différents formats de SIREN\n",
    "        patterns = [\n",
    "            r'\\b\\d{9}\\b',  # 9 chiffres consécutifs\n",
    "            r'\\b\\d{3}[\\s-]\\d{3}[\\s-]\\d{3}\\b',  # Format XXX XXX XXX ou XXX-XXX-XXX\n",
    "            r'\\b\\d{3}\\s+\\d{3}\\s+\\d{3}\\b'  # Format avec espaces multiples\n",
    "        ]\n",
    "        \n",
    "        numeros_siren = []\n",
    "        for pattern in patterns:\n",
    "            for match in re.finditer(pattern, texte):\n",
    "                # Nettoyer le numéro\n",
    "                siren_propre = re.sub(r'\\D', '', match.group())\n",
    "                if len(siren_propre) == 9:\n",
    "                    numeros_siren.append(siren_propre)\n",
    "        \n",
    "        # Supprimer les doublons tout en gardant l'ordre\n",
    "        return list(dict.fromkeys(numeros_siren))\n",
    "    \n",
    "    def extraire_siren_avec_spacy(self, texte):\n",
    "        \"\"\"Extraire les SIREN avec spaCy\"\"\"\n",
    "        doc = self.nlp(texte)\n",
    "        numeros_siren = []\n",
    "        \n",
    "        for ent in doc.ents:\n",
    "            if ent.label_ == \"SIREN\":\n",
    "                # Nettoyer le numéro extrait\n",
    "                siren_propre = re.sub(r'\\D', '', ent.text)\n",
    "                if len(siren_propre) == 9:\n",
    "                    numeros_siren.append(siren_propre)\n",
    "        \n",
    "        return list(dict.fromkeys(numeros_siren))\n",
    "    \n",
    "    def extraire_tous_siren(self, texte, valider=True):\n",
    "        \"\"\"Extraire tous les SIREN du texte en combinant spaCy et regex\"\"\"\n",
    "        # Extraction avec spaCy\n",
    "        siren_spacy = self.extraire_siren_avec_spacy(texte)\n",
    "        \n",
    "        # Extraction avec regex (fallback)\n",
    "        siren_regex = self.extraire_numeros_siren_regex(texte)\n",
    "        \n",
    "        # Combiner les résultats\n",
    "        tous_siren = list(dict.fromkeys(siren_spacy + siren_regex))\n",
    "        \n",
    "        # Valider si demandé\n",
    "        if valider:\n",
    "            siren_valides = [siren for siren in tous_siren if self.valider_siren(siren)]\n",
    "            siren_invalides = [siren for siren in tous_siren if not self.valider_siren(siren)]\n",
    "            return siren_valides, siren_invalides\n",
    "        \n",
    "        return tous_siren, []\n",
    "    \n",
    "    def analyser_fichier(self, chemin_fichier, encoding='utf-8'):\n",
    "        \"\"\"Analyser un fichier texte pour extraire les SIREN\"\"\"\n",
    "        try:\n",
    "            with open(chemin_fichier, 'r', encoding=encoding) as f:\n",
    "                texte = f.read()\n",
    "            \n",
    "            siren_valides, siren_invalides = self.extraire_tous_siren(texte)\n",
    "            \n",
    "            return {\n",
    "                'fichier': chemin_fichier,\n",
    "                'siren_valides': siren_valides,\n",
    "                'siren_invalides': siren_invalides,\n",
    "                'nb_valides': len(siren_valides),\n",
    "                'nb_invalides': len(siren_invalides)\n",
    "            }\n",
    "        \n",
    "        except FileNotFoundError:\n",
    "            print(f\"Erreur: Le fichier {chemin_fichier} n'existe pas.\")\n",
    "            return None\n",
    "        except UnicodeDecodeError:\n",
    "            print(f\"Erreur d'encodage. Tentative avec latin-1...\")\n",
    "            try:\n",
    "                with open(chemin_fichier, 'r', encoding='latin-1') as f:\n",
    "                    texte = f.read()\n",
    "                siren_valides, siren_invalides = self.extraire_tous_siren(texte)\n",
    "                return {\n",
    "                    'fichier': chemin_fichier,\n",
    "                    'siren_valides': siren_valides,\n",
    "                    'siren_invalides': siren_invalides,\n",
    "                    'nb_valides': len(siren_valides),\n",
    "                    'nb_invalides': len(siren_invalides)\n",
    "                }\n",
    "            except Exception as e:\n",
    "                print(f\"Erreur lors de la lecture du fichier: {e}\")\n",
    "                return None\n",
    "    \n",
    "    def sauvegarder_resultats_csv(self, resultats, dossier_sortie=\"resultats\"):\n",
    "        \"\"\"Sauvegarder les résultats dans un fichier CSV\"\"\"\n",
    "        if not resultats:\n",
    "            print(\"Aucun résultat à sauvegarder.\")\n",
    "            return None\n",
    "        \n",
    "        # Créer le dossier de sortie\n",
    "        os.makedirs(dossier_sortie, exist_ok=True)\n",
    "        \n",
    "        # Préparer les données\n",
    "        donnees = []\n",
    "        for i, siren in enumerate(resultats['siren_valides'], 1):\n",
    "            donnees.append({\n",
    "                'siren': siren,\n",
    "                'valide': True,\n",
    "                'fichier_source': os.path.basename(resultats['fichier'])\n",
    "            })\n",
    "        \n",
    "        for i, siren in enumerate(resultats['siren_invalides'], len(resultats['siren_valides']) + 1):\n",
    "            donnees.append({\n",
    "                'siren': siren,\n",
    "                'valide': False,\n",
    "                'fichier_source': os.path.basename(resultats['fichier'])\n",
    "            })\n",
    "        \n",
    "        # Créer le DataFrame et sauvegarder\n",
    "        df = pd.DataFrame(donnees)\n",
    "        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')\n",
    "        nom_fichier_csv = f\"{dossier_sortie}/siren_extraits_{timestamp}.csv\"\n",
    "        df.to_csv(nom_fichier_csv, index=False, encoding='utf-8')\n",
    "        \n",
    "        print(f\"Résultats sauvegardés dans: {nom_fichier_csv}\")\n",
    "        return nom_fichier_csv\n",
    "    def sauvegarder_resultats_json(self, resultats, dossier_sortie=\"resultats\"):\n",
    "        \"\"\"Sauvegarder les résultats dans un fichier JSON\"\"\"\n",
    "        if not resultats:\n",
    "            print(\"Aucun résultat à sauvegarder.\")\n",
    "            return None\n",
    "\n",
    "        # Créer le dossier de sortie\n",
    "        os.makedirs(dossier_sortie, exist_ok=True)\n",
    "\n",
    "        # Préparer les données au format JSON\n",
    "        donnees = {\n",
    "            \"fichier_source\": os.path.basename(resultats[\"fichier\"]),\n",
    "            \"date_extraction\": datetime.now().isoformat(),\n",
    "            \"siren_valides\": [\n",
    "                {\"siren\": s, \"valide\": True} for s in resultats[\"siren_valides\"]\n",
    "            ],\n",
    "            \"siren_invalides\": [\n",
    "                {\"siren\": s, \"valide\": False} for s in resultats[\"siren_invalides\"]\n",
    "            ]\n",
    "        }\n",
    "\n",
    "        # Sauvegarder dans un fichier JSON\n",
    "        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')\n",
    "        nom_fichier_json = f\"{dossier_sortie}/siren_extraits_{timestamp}.json\"\n",
    "        \n",
    "        with open(nom_fichier_json, \"w\", encoding=\"utf-8\") as f:\n",
    "            json.dump(donnees, f, indent=4, ensure_ascii=False)\n",
    "\n",
    "        print(f\"Résultats sauvegardés dans : {nom_fichier_json}\")\n",
    "        return nom_fichier_json\n",
    "    def afficher_resultats(self, resultats):\n",
    "        \"\"\"Afficher un résumé des résultats\"\"\"\n",
    "        if not resultats:\n",
    "            print(\"Aucun résultat à afficher.\")\n",
    "            return\n",
    "        \n",
    "        print(f\"\\n=== RÉSULTATS D'EXTRACTION SIREN ===\")\n",
    "        print(f\"Fichier analysé: {resultats['fichier']}\")\n",
    "        print(f\"SIREN valides trouvés: {resultats['nb_valides']}\")\n",
    "        print(f\"SIREN invalides trouvés: {resultats['nb_invalides']}\")\n",
    "        \n",
    "        if resultats['siren_valides']:\n",
    "            print(f\"\\nSIREN valides:\")\n",
    "            for siren in resultats['siren_valides']:\n",
    "                print(f\"  - {siren}\")\n",
    "        \n",
    "        if resultats['siren_invalides']:\n",
    "            print(f\"\\nSIREN invalides (échec validation):\")\n",
    "            for siren in resultats['siren_invalides']:\n",
    "                print(f\"  - {siren}\")\n",
    "\n",
    "\n",
    "def main():\n",
    "    \"\"\"Fonction principale pour utiliser l'extracteur SIREN\"\"\"\n",
    "    # Initialiser l'extracteur\n",
    "    extracteur = SirenExtractor()\n",
    "    \n",
    "    # Chemin du fichier à analyser (modifiez selon vos besoins)\n",
    "    chemin_fichier = \"D:/Bureau/Stage La gazette/projet ia n°de siren/annonces légales/test annonce légale saone et loire 0206.txt\"\n",
    "    \n",
    "    # Analyser le fichier\n",
    "    print(\"Analyse du fichier en cours...\")\n",
    "    resultats = extracteur.analyser_fichier(chemin_fichier)\n",
    "    \n",
    "    if resultats:\n",
    "        # Afficher les résultats\n",
    "        extracteur.afficher_resultats(resultats)\n",
    "        \n",
    "        # Sauvegarder en CSV\n",
    "        fichier_csv = extracteur.sauvegarder_resultats_csv(resultats)\n",
    "\n",
    "        # Sauvegarde en JSON\n",
    "        fichier_JSON = extracteur.sauvegarder_resultats_json(resultats)\n",
    "\n",
    "        print(f\"\\n✅ Exctraction terminée avec succès!\")\n",
    "        \n",
    "    else:\n",
    "        print(\"❌ Erreur lors de l'analyse du fichier.\")\n",
    "    \n",
    "    # Lancer l'extraction principale\n",
    "main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
